# Generated by Django 5.1.4 on 2025-02-11 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the transaction')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', help_text='Type of transaction, either income or expense', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The monetary value of the transaction', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='A brief description of the transaction')),
                ('category', models.ForeignKey(blank=True, help_text='Category this transaction belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tracker.category')),
                ('user', models.ForeignKey(help_text='The user this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
