# Generated by Django 5.1.4 on 2025-02-13 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2025, help_text='Year of the budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total available budget', max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=2, help_text='Month of the budget'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'month', 'year')},
        ),
    ]
