# Generated by Django 5.1.4 on 2025-02-13 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_category_user_transaction_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the savings goal', max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Target amount to save', max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount saved so far', max_digits=10)),
                ('deadline', models.DateField(help_text='Deadline to reach the goal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
