# Generated by Django 5.1.4 on 2025-02-14 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_userbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
